/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#ffb596',
        'surface-bright': '#373942',
        'primary-container': '#2563eb',
        'on-secondary-fixed-variant': '#004395',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#360f00',
        'secondary-fixed-dim': '#adc6ff',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#0053db',
        'on-surface': '#e1e2ed',
        'inverse-on-surface': '#2e3039',
        'primary-fixed-dim': '#b4c5ff',
        'error-container': '#93000a',
        'outline-variant': '#434655',
        'secondary-fixed': '#d8e2ff',
        'on-background': '#e1e2ed',
        'on-surface-variant': '#c3c6d7',
        'on-primary-container': '#eeefff',
        'on-error': '#690005',
        outline: '#8d90a0',
        'on-tertiary': '#581e00',
        'surface-container': '#1d1f27',
        'on-secondary-container': '#e6ecff',
        'on-tertiary-container': '#ffede6',
        surface: '#11131b',
        'tertiary-fixed-dim': '#ffb596',
        'surface-container-highest': '#32343d',
        'on-error-container': '#ffdad6',
        secondary: '#adc6ff',
        'surface-tint': '#b4c5ff',
        'on-secondary-fixed': '#001a42',
        background: '#11131b',
        'surface-dim': '#11131b',
        primary: '#b4c5ff',
        'surface-container-lowest': '#0c0e16',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-variant': '#32343d',
        'secondary-container': '#0566d9',
        'on-primary': '#002a78',
        'tertiary-container': '#bc4800',
        'inverse-surface': '#e1e2ed',
        'on-primary-fixed': '#00174b',
        'on-secondary': '#002e6a',
        'tertiary-fixed': '#ffdbcd',
        'surface-container-high': '#282a32',
        'surface-container-low': '#191b23',
        'primary-fixed': '#dbe1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'card-padding': '24px',
        'panel-gap': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1440px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'display-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      keyframes: {
        'float-1': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-15px) rotate(2deg)' },
        },
        'float-2': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(-2deg)' },
        },
        'float-3': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(1deg)' },
        },
      },
      animation: {
        'float-1': 'float-1 6s ease-in-out infinite',
        'float-2': 'float-2 8s ease-in-out infinite reverse',
        'float-3': 'float-3 7s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
